# Generated by Django 2.0.2 on 2018-03-27 17:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import main.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=256)),
                ('verifycode', models.CharField(default=main.utils.Tools.get_code, help_text='For Staff Regist', max_length=4, unique=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='DLI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_license_no', models.CharField(max_length=32, unique=True, verbose_name='Driving License No.')),
                ('driver_code', models.CharField(max_length=16)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
            ],
            options={
                'verbose_name': 'Driver License Infomation',
                'verbose_name_plural': 'Driver License Info',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='5976237056698047', max_length=16)),
                ('amount', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('cancel', 'Cancel'), ('close', 'Close')], default='open', max_length=6)),
                ('settle_status', models.CharField(choices=[('unsettle', 'Unsettle'), ('settle', 'Settle')], default='unsettle', max_length=8)),
                ('pay_status', models.CharField(choices=[('paid', 'Paid'), ('refunding', 'Refunding'), ('refunded', 'Refunded')], default='paid', max_length=9)),
                ('remake', models.TextField(blank=True, max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='OrderVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='5976237056698047', max_length=16)),
                ('amount', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('cancel', 'Cancel'), ('close', 'Close')], default='open', max_length=6)),
                ('settle_status', models.CharField(choices=[('unsettle', 'Unsettle'), ('settle', 'Settle')], default='unsettle', max_length=8)),
                ('pay_status', models.CharField(choices=[('paid', 'Paid'), ('refunding', 'Refunding'), ('refunded', 'Refunded')], default='paid', max_length=9)),
                ('remake', models.TextField(blank=True, max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='PPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_no', models.CharField(max_length=32, unique=True, verbose_name='Passport No.')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_of_birth', models.DateField()),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
            ],
            options={
                'verbose_name': 'Passport Infomation',
                'verbose_name_plural': 'Passport Info',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(help_text='name', max_length=64, unique=True)),
                ('phone', models.CharField(help_text='your phone', max_length=16, unique=True)),
                ('nickname', models.CharField(help_text='nick name', max_length=64)),
                ('introduction', models.TextField(blank=True, max_length=256)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('status', models.CharField(blank=True, choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=16, null=True)),
                ('hour_pay', models.FloatField(blank=True, default=0.0)),
                ('work_status', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop')], default='start', max_length=5)),
                ('driver', models.BooleanField(default=False, verbose_name='Driver ?')),
                ('tourguide', models.BooleanField(default=False, verbose_name='TourGuide ?')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='main.Company')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TLI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=64, unique=True, verbose_name='TourGuide No.')),
                ('language', models.CharField(choices=[('english', 'English'), ('chinese', 'Chinese')], default='chinese', max_length=7)),
                ('date_of_expiry', models.DateField()),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TLI', to='main.Staff')),
            ],
            options={
                'verbose_name': 'TourGuide License Infomation',
                'verbose_name_plural': 'TourGuide License Info',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_no', models.CharField(max_length=16, unique=True)),
                ('chassis_no', models.CharField(max_length=32, unique=True)),
                ('traffic_plate_no', models.CharField(max_length=16, unique=True)),
                ('exp_date', models.DateField()),
                ('reg_date', models.DateField()),
                ('ins_exp', models.DateField()),
                ('policy_no', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(blank=True, choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=16, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='main.Company')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('car', 'Car'), ('suv', 'SUV'), ('mpv', 'MPV'), ('van', 'VAN'), ('bus', 'BUS'), ('luxury', 'Luxury')], default='Car', max_length=6)),
                ('name', models.CharField(max_length=64)),
                ('num', models.IntegerField(default=5, verbose_name='number of passenger')),
                ('pay', models.FloatField()),
                ('photo', models.ImageField(blank=True, upload_to='vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Model',
                'verbose_name_plural': 'Vehicle Model',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='main.VehicleModel'),
        ),
        migrations.AddField(
            model_name='ppi',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PPI', to='main.Staff'),
        ),
        migrations.AddField(
            model_name='ordervehicle',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.Vehicle'),
        ),
        migrations.AddField(
            model_name='orderstaff',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.Staff'),
        ),
        migrations.AddField(
            model_name='dli',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DLI', to='main.Staff'),
        ),
    ]
