# Generated by Django 2.0.2 on 2018-03-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='pay',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='orderstaff',
            name='order_id',
            field=models.CharField(default='1699620889845143', max_length=16),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='order_id',
            field=models.CharField(default='1699620889845143', max_length=16),
        ),
    ]
