# Generated by Django 2.0.1 on 2018-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_point',
            new_name='end_addr',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_point',
            new_name='start_addr',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2010),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='num_of_pass',
            field=models.IntegerField(default=5, verbose_name='number of passenger'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rate',
            field=models.FloatField(blank=True, default=0.0, help_text='Rent per day'),
        ),
    ]
