# Generated by Django 2.0.2 on 2018-03-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180327_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstaff',
            name='order_id',
            field=models.CharField(default='4500082497505602', max_length=16),
        ),
        migrations.AlterField(
            model_name='orderstaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.Staff'),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='order_id',
            field=models.CharField(default='4500082497505602', max_length=16),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.Vehicle'),
        ),
    ]
