# Generated by Django 2.0.2 on 2018-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180327_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstaff',
            options={'verbose_name': 'Staff Orders', 'verbose_name_plural': 'Staff Orders'},
        ),
        migrations.AlterModelOptions(
            name='ordervehicle',
            options={'verbose_name': 'Vehicle Orders', 'verbose_name_plural': 'Vehicle Orders'},
        ),
        migrations.AddField(
            model_name='orderstaff',
            name='pickup_type',
            field=models.CharField(choices=[('self', 'Pick up car by yourself'), ('shop', 'Go to the shop')], default='self', max_length=4),
        ),
        migrations.AddField(
            model_name='ordervehicle',
            name='pickup_type',
            field=models.CharField(choices=[('self', 'Pick up car by yourself'), ('shop', 'Go to the shop')], default='self', max_length=4),
        ),
        migrations.AlterField(
            model_name='orderstaff',
            name='order_id',
            field=models.CharField(default='9475251053256925', max_length=16),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='order_id',
            field=models.CharField(default='9475251053256925', max_length=16),
        ),
    ]
