# Generated by Django 2.0.2 on 2018-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180327_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstaff',
            name='pickup_type',
        ),
        migrations.AddField(
            model_name='orderstaff',
            name='client_type',
            field=models.CharField(choices=[('company', 'Company'), ('personal', 'Personal')], default='company', max_length=8),
        ),
        migrations.AddField(
            model_name='ordervehicle',
            name='client_type',
            field=models.CharField(choices=[('company', 'Company'), ('personal', 'Personal')], default='company', max_length=8),
        ),
        migrations.AlterField(
            model_name='orderstaff',
            name='order_id',
            field=models.CharField(default='5445416861577693', max_length=16),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='order_id',
            field=models.CharField(default='5445416861577693', max_length=16),
        ),
    ]
