# Generated by Django 2.0.2 on 2018-03-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180327_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstaff',
            name='order_id',
            field=models.CharField(default='3641101662993478', max_length=16),
        ),
        migrations.AlterField(
            model_name='orderstaff',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cancel', 'Cancel'), ('complete', 'Complete')], default='open', max_length=8),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='order_id',
            field=models.CharField(default='3641101662993478', max_length=16),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cancel', 'Cancel'), ('complete', 'Complete')], default='open', max_length=8),
        ),
    ]
