# Generated by Django 2.0.2 on 2018-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180327_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstaff',
            name='staff_confirm',
            field=models.CharField(choices=[('wait', 'Waiting for confirmation'), ('agree', 'Agree'), ('refuse', 'Refuse')], default='wait', max_length=6),
        ),
        migrations.AlterField(
            model_name='orderstaff',
            name='order_id',
            field=models.CharField(default='6742323191109481', max_length=16),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='order_id',
            field=models.CharField(default='6742323191109481', max_length=16),
        ),
    ]
