# Generated by Django 2.0.2 on 2018-03-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180327_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordervehicle',
            name='settle_status',
        ),
        migrations.AlterField(
            model_name='orderstaff',
            name='order_id',
            field=models.CharField(default='1759310593230080', max_length=16),
        ),
        migrations.AlterField(
            model_name='ordervehicle',
            name='order_id',
            field=models.CharField(default='1759310593230080', max_length=16),
        ),
    ]
